name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to true to destroy the infrastructure'
        required: true
        default: 'false'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.5

    - name: Azure CLI Login
      uses: azure/login@v1.6.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.event.inputs.destroy != 'true'
      run: terraform apply -auto-approve

    - name: Terraform Import Existing Resources
      if: github.event.inputs.destroy == 'true'
      run: |
        terraform import azurerm_resource_group.ta-rg /subscriptions/YOUR_SUBSCRIPTION_ID/resourceGroups/ta-resources || true
        terraform import azurerm_virtual_network.ta-vnet /subscriptions/YOUR_SUBSCRIPTION_ID/resourceGroups/ta-resources/providers/Microsoft.Network/virtualNetworks/ta-vnet || true
        terraform import azurerm_network_security_group.ta-nsg /subscriptions/YOUR_SUBSCRIPTION_ID/resourceGroups/ta-resources/providers/Microsoft.Network/networkSecurityGroups/ta-nsg || true
        terraform import azurerm_public_ip.ta-pip /subscriptions/YOUR_SUBSCRIPTION_ID/resourceGroups/ta-resources/providers/Microsoft.Network/publicIPAddresses/ta-pip || true

    - name: Terraform Destroy
      if: github.event.inputs.destroy == 'true'
      run: terraform destroy -auto-approve
